# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# VIM mode
bindkey -v
bindkey "^R" history-incremental-search-backward

#FASD
PATH=$PATH:$HOME/fasd
eval "$(fasd --init auto)"

# For Xvfb and Jasmine
export DISPLAY=:0

# Customize to your needs...
# Execute the config files in .zsh.after

if [[ -s "${HOME}/.zsh.after/*.zsh" ]]; then
  for config_file ($HOME/.zsh.after/*.zsh) source $config_file
fi

# For pyenv
export PATH="${ZDOTDIR:-$HOME}/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# For Java
export JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/"

# For sdkman
export SDKMAN_DIR="${ZDOTDIR:-$HOME}/"
[[ -s "${ZDOTDIR:-$HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${ZDOTDIR:-$HOME}/.sdkman/bin/sdkman-init.sh"
