---
- name: Add openjdk ppa
  apt_repository: repo='ppa:openjdk-r/ppa'
  sudo: True

- name: Add GDAL apt repository
  apt_repository: repo='ppa:ubuntugis/ubuntugis-unstable'
  sudo: True

- name: Update apt
  apt: update_cache=yes
  sudo: True

- name: Install required packages
  apt: name={{item}} state=latest
  sudo: True
  with_items:
    - git-core
    - build-essential
    - ruby-dev
    - curl
    - zip
    - unzip
    - libgmp3-dev
    - libcurl4-openssl-dev
    - libv8-dev
    - vim
    - tree
    - tmux
    - python-software-properties

