---
- name: Add postgres user to sudoers
  template: src=sudoers.j2 dest=/etc/sudoers.d/postgres owner=0 group=0 mode=0440
  sudo: True

- name: Install required packages
  apt: name={{item}} state=present
  sudo: True
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-contrib

- name: Ensure DB user has access to the DB
  postgresql_user: name={{app_user}} password={{postgresql_password}} state=present role_attr_flags=SUPERUSER
  sudo: True
  sudo_user: postgres

