---
- name: Grab RVM keys
  shell: curl -#LO https://rvm.io/mpapis.asc

- name: Import RVM keys
  shell: gpg --import mpapis.asc

- name: Install rvm
  shell: \curl -sSL https://get.rvm.io | bash -s stable --autolibs=3

- name: Install ruby
  shell: ~/.rvm/bin/rvm install --default {{ ruby }} creates=~/.rvm/rubies/{{ ruby }}

- name: Update bundler
  shell: ~/.rvm/rubies/{{ ruby }}/bin/gem update bundler -v 1.8


