---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - git-core
    - build-essential
    - curl
    - libcurl4-openssl-dev
    - libv8-dev
    - vim
    - tree
    - tmux
    - unzip
