---
- name: Install required packages
  apt: name={{item}} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-contrib

- name: Ensure DB user has access to the DB
  postgresql_user:
    name: "{{ box_user }}"
    password: "{{ postgresql_password }}"
    state: present
    role_attr_flags: SUPERUSER
  become: True
  become_user: postgres
