# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# VIM mode
bindkey -v
bindkey "^R" history-incremental-search-backward

#FASD
PATH=$PATH:$HOME/fasd
eval "$(fasd --init auto)"

# For Xvfb and Jasmine
export DISPLAY=:0

# For java
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-i386/jre

# Execute the config files in .zsh.after

if [[ -s "${HOME}/.zsh.after/*.zsh" ]]; then
  for config_file ($HOME/.zsh.after/*.zsh) source $config_file
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
